apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  lables: 
    project: roboshop
    purpose: multi-container-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux
    command: ["sleep", "10000"]
    