apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels: 
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is created to demonstrate pod annotations"
spec: 
  containers:
  - name: nginx
    image: nginx
    