apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:  ## soft limit
        memory: "60Mi"
        cpu: "100m"
      limits:    ## hard limit
        memory: "100Mi"
        cpu: "150m"