apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    purpose: demonstrate-env
  spec:
    containers:
    - name : nginx
      image: nginx
      env:
      - name: COURSE
        value: KUBERNETES
      - name: LEARNER
        value: "MOHAN VAMSI R"