apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  ## Deployment labels
  labels:
    purpose: deployement-demo
    project: roboshop
    app: nginx
spec:
  replicas: 2
  ## these are the labels replica set use to create pod replicas, this should match pod labels
  selector:
    matchLabels:
      purpose: deployement-demo
      project: roboshop
      app: nginx
  ## This is pod definition
  template:
    metadata:
      labels:
        purpose: deployement-demo
        project: roboshop
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels: 
    purpose: deployement-demo
    project: roboshop
    app: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: deployement-demo
    project: roboshop
    app: nginx
  ports:
    - protocol: TCP
      port: 80 ## service port
      targetPort: 80 ## service port