apiVersion: v1
kind: Service
metadata:
  name: ngnix-headless-svc
  labels:
    purpose: statefulset
    project: roboshop
spec:
  selector:
    purpose: stateful-set
    project: roboshop
  ports:
  - port: 80
    name: web
  clusterIP: None

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
spec:
  selector:
    matchLabels:
      purpose: statefulset   ### this should match .spec.template.metadata.labels
      project: roboshop
  serviceName: ngnix-headless-svc    ## this should be headless service
  replicas: 3
  template:
    metadata:
      labels:
        purpose: statefulset
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx  
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  ###  This is nothing but PVC, we can create here directly
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 2Gi
